name: titanic-survival-prediction
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - scikit-learn
  - jupyterlab
  - seaborn
  - mlflow
  - fastapi
  - streamlit
  - pytest
  - requests
  - joblib
  - pip